version: '3.3'
services:
  myapp:
    image: docker.io/bitnami/codeigniter:3
    ports:
      - '8000:8000'
    volumes:
      - './app/codeigniter:/app/myapp'
    depends_on:
      - mariadb
    networks:
      - mynet
    
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    ports:
      - 3306:3306
    environment:
      - MARIADB_DATABASE=Videos
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './Videos.sql:/docker-entrypoint-initdb.d/Videos.sql'
    networks:
      - mynet

  phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - mariadb
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
